# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bernoulli_likelihood <- function(data, beta, formula, varName) {
    .Call('_blatent_bernoulli_likelihood', PACKAGE = 'blatent', data, beta, formula, varName)
}

bernoulli_likelihood2 <- function(data, parameters, formula, varName) {
    .Call('_blatent_bernoulli_likelihood2', PACKAGE = 'blatent', data, parameters, formula, varName)
}

bernoulliLikelihoodPtr <- function(fstr) {
    .Call('_blatent_bernoulliLikelihoodPtr', PACKAGE = 'blatent', fstr)
}

testingLikeFunc <- function(func, data, parameters, formula, varName) {
    .Call('_blatent_testingLikeFunc', PACKAGE = 'blatent', func, data, parameters, formula, varName)
}

bin2dec_Rcpp <- function(binaryVector, nAttributes, baseVector) {
    .Call('_blatent_bin2dec_Rcpp', PACKAGE = 'blatent', binaryVector, nAttributes, baseVector)
}

getMeanAndCov_HH2006L1 <- function(X, W, Y, invBetaCov, invBetaCovBetaMean) {
    .Call('_blatent_getMeanAndCov_HH2006L1', PACKAGE = 'blatent', X, W, Y, invBetaCov, invBetaCovBetaMean)
}

logdN01 <- function(x, pars, data) {
    .Call('_blatent_logdN01', PACKAGE = 'blatent', x, pars, data)
}

create_xptr <- function(fstr) {
    .Call('_blatent_create_xptr', PACKAGE = 'blatent', fstr)
}

rks_Rcpp <- function(n, r) {
    .Call('_blatent_rks_Rcpp', PACKAGE = 'blatent', n, r)
}

testFunc <- function(x) {
    .Call('_blatent_testFunc', PACKAGE = 'blatent', x)
}

rmvnorm_Rcpp <- function(n, mu, sigma) {
    .Call('_blatent_rmvnorm_Rcpp', PACKAGE = 'blatent', n, mu, sigma)
}

rtmvnormRejection_Rcpp <- function(mu, sigma, D, maxSample, previous) {
    .Call('_blatent_rtmvnormRejection_Rcpp', PACKAGE = 'blatent', mu, sigma, D, maxSample, previous)
}

sampleBernoulliUnits <- function(data, variables, varName) {
    .Call('_blatent_sampleBernoulliUnits', PACKAGE = 'blatent', data, variables, varName)
}

sampleMultivariateBernoulliUnits <- function(data, variables, varName) {
    .Call('_blatent_sampleMultivariateBernoulliUnits', PACKAGE = 'blatent', data, variables, varName)
}

sampleMultivariateBernoulliUnits2 <- function(data, variables, varName) {
    .Call('_blatent_sampleMultivariateBernoulliUnits2', PACKAGE = 'blatent', data, variables, varName)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_blatent_RcppExport_registerCCallable', PACKAGE = 'blatent')
})
